const ROLES=[
['Ученик / ученица','Бесплатное основное общее образование, уважительное отношение и защита от насилия'],
['Спортсмен','Охрана здоровья, безопасные условия тренировок, страхование от несчастных случаев'],
['Волонтёр (14 лет)','Участие в волонтёрской деятельности, инструктаж и безопасные условия'],
['Интернет-пользователь','Доступ к информации, поиск сведений и защита персональных данных'],
['Велосипедист (14 лет)','Безопасное передвижение по велодорожкам и разрешённым участкам дорог'],
['Читатель','Доступ к информации из разных источников, включая книги и электронные каталоги'],
['Потребитель (13 лет)','Мелкие бытовые сделки, информация о товаре и возврат некачественного товара'],
['Пассажир троллейбуса','Безопасность перевозок, информация о маршруте и тарифах'],
['Сын / дочь','Защита прав родителями и общение с родственниками'],
['Пациент (15 лет)','Самостоятельное информированное согласие или отказ от медицинского вмешательства по общему правилу'],
['Друг / подруга','Личная жизнь, свобода общения и тайна переписки'],
['Гражданин','Жизнь, достоинство, свобода и личная неприкосновенность'],
['Участник выставки начинающих художников','Свобода творчества и авторское право'],
['Верующий человек','Свобода совести и вероисповедания'],
['Посетитель кафе','Достоверная информация о составе, весе и цене блюд'],
['Работник (14 лет)','Лёгкий труд с согласия законного представителя, сокращённая рабочая неделя и распоряжение заработком'],
['Зритель','Участие в культурной жизни и доступ к культурным мероприятиям'],
['Участник объединения','Участие в детских объединениях с 8 лет, в молодёжных — с 14 лет'],
['Клиент банка (14 лет)','Открытие банковского счёта с согласия законного представителя и распоряжение вкладом в пределах закона'],
['Участник онлайн-сообщества','Свобода мысли и слова, доступ к информации и её распространение']
];
const $=s=>document.querySelector(s),shuffle=a=>{let b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b},esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let game='bingo',state=null,timer=null;
const work=$('#workspace');
function stop(){clearInterval(timer);timer=null}
function heading(title,desc){return `<div class="boardhead"><div><h2>${title}</h2><p>${desc}</p></div><button class="secondary" id="rulebtn">Правила</button></div>`}
function bindRules(){$('#rulebtn').onclick=rules}
const HISTORY_KEY='teen-rights-bingo-used-v1';
let historyFallback=[];
function readHistory(){try{const ids=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');if(!Array.isArray(ids))return [];return [...new Set(ids.filter(id=>BINGO.some(c=>c.id===id)))];}catch{return historyFallback;}}
function saveHistory(ids){historyFallback=ids;try{localStorage.setItem(HISTORY_KEY,JSON.stringify(ids));}catch{}}
function takeNewRound(count=4){const used=readHistory();const pool=shuffle(BINGO.filter(c=>!used.includes(c.id))).slice(0,count);if(pool.length!==count)return null;saveHistory([...used,...pool.map(c=>c.id)]);return pool;}
function setup(){stop();state=null;if(game==='slang'){slangSetup();return;}if(game==='route'){routeSetup();return;}work.innerHTML=heading(game==='bingo'?'Права подростка. Бинго':'Социальная роль и право',game==='bingo'?'Найди право, которое подходит к ситуации.':'У каждого из нас много ролей. Найди права для каждой.')+`<div class="setup"><div>${game==='bingo'?'':'<span class="tag">20 пар</span><span class="tag">Онлайн-тренировка</span>'}<h3>${game==='bingo'?'Твоя задача — закрыть все клетки на своих картах':'Соедини роль и право'}</h3><p>${game==='bingo'?'В каждой игре — одна бинго-карта с 4 правами. Прочитай ситуацию и выбери подходящее право. Верный ответ закроет клетку. Ошибся? Попробуй ещё раз — здесь можно учиться в своём темпе.':'Выбери карточку роли слева, затем подходящее право справа. Собери все 20 пар в своём темпе.'}</p><div class="options">${game==='bingo'?`<span>Новых ситуаций: <strong>${32-readHistory().length} из 32</strong>. Повторов до конца круга не будет.</span>`:''}</div><button class="primary" id="start">Начать игру</button></div><div class="previewgrid" aria-hidden="true">${(game==='bingo'?['Б','И','Н','Г','О','!','✓','?']:['Р','О','Л','Ь','П','Р','А','В','О','✓','?','!']).map(s=>`<span>${s}</span>`).join('')}</div></div>`;bindRules();if(game==='bingo'&&readHistory().length===32){$('.setup h3').textContent='Все 32 ситуации уже сыграны';$('.setup p').textContent='Ты прошёл весь набор! Начни новый круг, чтобы ещё раз закрепить знания. Ситуации из предыдущего круга будут повторяться.';$('#start').textContent='Начать новый круг';$('#start').onclick=()=>{saveHistory([]);start()};}else $('#start').onclick=start}
function start(){if(game==='bingo'){let pool=takeNewRound(4);if(!pool){setup();return;}state={pool,order:shuffle(pool),done:new Set(),index:0,errors:0,choices:shuffle(pool),locked:false};renderBingo()}else{state={done:new Set(),selected:null,errors:0,roleOrder:shuffle(ROLES.map((_,i)=>i)),rightOrder:shuffle(ROLES.map((_,i)=>i))};renderRoles();}}
function feedback(t,good){const el=$('#feedback');el.textContent=t;el.className='feedback '+(good?'good':'bad')}
function renderBingo(){const s=state,q=s.order[s.index];work.innerHTML=heading('Права подростка. Бинго',`Закрыто ${s.done.size} из ${s.pool.length} клеток · Ошибок: ${s.errors}`)+`<div class="progress"><span style="width:${s.done.size/s.pool.length*100}%"></span></div><div class="gamebody"><div class="scenario"><span class="counter">СИТУАЦИЯ · ХОД ${s.index+1}/${s.pool.length}</span><h3>${esc(q.text)}</h3><p class="muted">Какое право связано с этой ситуацией?</p><div id="feedback" class="feedback" role="status" aria-live="polite"></div><button id="next" class="primary" hidden>Следующая ситуация</button></div><div class="bingocards">${Array.from({length:s.pool.length/4},(_,i)=>`<section class="bingocard"><h3>Бинго-карта ${i+1}<span>4 клетки</span></h3><div class="rightsgrid">${s.choices.slice(i*4,i*4+4).map(c=>`<button data-id="${c.id}" class="rightcard ${s.done.has(c.id)?'done':''}" ${s.done.has(c.id)?'disabled':''}>${s.done.has(c.id)?'✓ ':''}${esc(c.right)}</button>`).join('')}</div></section>`).join('')}</div></div>`;bindRules();work.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{if(s.locked)return;if(+b.dataset.id===q.id){s.done.add(q.id);s.locked=true;b.classList.add('done');b.textContent='✓ '+q.right;b.disabled=true;feedback('Верно! '+(q.note||'Это право соответствует ситуации.'),true);$('#next').hidden=false;$('#next').textContent=s.done.size===s.pool.length?'Объявить «Бинго!»':'Следующая ситуация';work.querySelector('.boardhead p').textContent=`Закрыто ${s.done.size} из ${s.pool.length} клеток · Ошибок: ${s.errors}`;work.querySelector('.progress span').style.width=s.done.size/s.pool.length*100+'%'}else{s.errors++;feedback('Пока не совпало. Подумай, что именно затронуто в этой ситуации.',false);work.querySelector('.boardhead p').textContent=`Закрыто ${s.done.size} из ${s.pool.length} клеток · Ошибок: ${s.errors}`}});$('#next').onclick=()=>{if(s.done.size===s.pool.length)finish(true);else{s.index++;s.locked=false;renderBingo()}}}
const format=n=>`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;
function renderRoles(){const s=state;work.innerHTML=heading('Социальная роль и право','Сначала выбери роль, затем — её право.')+`<div class="gamestatus"><strong id="paircount">${s.done.size} / 20 пар</strong><span id="mistakes">Ошибок: ${s.errors}</span><button id="end" class="secondary">Завершить</button></div><div id="feedback" class="feedback" role="status" aria-live="polite">Выбери любую роль слева.</div><div class="rolecols"><div><h3>Социальная роль</h3><div class="rolelist">${s.roleOrder.map(i=>`<button data-role="${i}" class="${s.done.has(i)?'done':''}" ${s.done.has(i)?'disabled':''}>${s.done.has(i)?'✓ ':''}${esc(ROLES[i][0])}</button>`).join('')}</div></div><div><h3>Право</h3><div class="rolelist">${s.rightOrder.map(i=>`<button data-right="${i}" class="${s.done.has(i)?'done':''}" ${s.done.has(i)?'disabled':''}>${s.done.has(i)?'✓ ':''}${esc(ROLES[i][1])}</button>`).join('')}</div></div></div>`;bindRules();$('#end').onclick=()=>finish(false);work.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{s.selected=+b.dataset.role;work.querySelectorAll('[data-role]').forEach(el=>{el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',el===b?'true':'false')});feedback('Теперь выбери право для роли «'+ROLES[s.selected][0]+'».',true)});work.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{if(s.selected===null){feedback('Сначала выбери роль в левом столбце.',false);return}if(+b.dataset.right===s.selected){s.done.add(s.selected);s.selected=null;renderRoles();feedback('Верная пара! Выбери следующую роль.',true);if(s.done.size===20)finish(true)}else{s.errors++;$('#mistakes').textContent='Ошибок: '+s.errors;feedback('Эта пара не подходит. Попробуй другое право.',false)}})}
function finish(win){stop();const s=state;work.innerHTML=`<div class="results"><span class="eyebrow">${win?'ОТЛИЧНАЯ ИГРА':'ТРЕНИРОВКА ЗАВЕРШЕНА'}</span><h2>${game==='bingo'?'Бинго! Все твои карты закрыты.':win?'Все пары найдены!':'Вот твой результат'}</h2><div class="resultnum">${s.done.size}<span style="font-size:24px"> / ${game==='bingo'?s.pool.length:20}</span></div><p>${game==='bingo'?'прав на твоих бинго-картах':'пар «роль — право»'} · Ошибок: ${s.errors}</p><p>Чем чаще разбираешь жизненные ситуации, тем легче замечать права в повседневной жизни.</p><button id="again" class="primary">Играть ещё раз</button><button id="other" class="secondary">${game==='bingo'?'Попробовать роли':'Попробовать бинго'}</button>${game==='roles'&&!win?`<details><summary>Посмотреть ненайденные пары</summary>${ROLES.map((r,i)=>s.done.has(i)?'':`<p><strong>${esc(r[0])}</strong><br>${esc(r[1])}</p>`).join('')}</details>`:''}</div>`;$('#again').onclick=setup;$('#other').onclick=()=>choose(game==='bingo'?'roles':'bingo')}
function choose(g){game=g;document.querySelectorAll('[data-game]').forEach(b=>b.setAttribute('aria-selected',b.dataset.game===g?'true':'false'));work.setAttribute('aria-labelledby','tab-'+g);setup()}
function rules(){const bingo=game==='bingo';$('#rulescontent').innerHTML=`<span class="eyebrow">КАК ИГРАТЬ</span><h2>${bingo?'Права подростка. Бинго':'Социальная роль и право'}</h2><ol>${(bingo?['В комплекте 8 бинго-карт по 4 клетки, 32 карточки с правами, 32 ситуации и 32 жетона. В этой онлайн-тренировке всегда одна карта с 4 правами и одна ситуация на экране. При новом запуске сайт даёт новые ситуации и права без повторов до конца набора.','Прочитай ситуацию и найди соответствующее право на одной из своих бинго-карт.','Верная карточка отмечается галочкой. Если ошибся, попробуй снова.','Переходи к следующей ситуации. Закрой все 4 клетки на своей карте и объяви «Бинго!». Верные пары «ситуация — право» проверяются автоматически. Пройденные ситуации не повторяются до конца набора из 32; новый круг начинается только по твоему нажатию.']:['Нажми на социальную роль в левом столбце.','Выбери соответствующее право в правом столбце.','Верная пара отмечается галочками. Ошибка не убирает карточки.','Собери все 20 пар. Ограничения по времени нет; можно завершить тренировку кнопкой «Завершить».']).map(t=>'<li>'+t+'</li>').join('')}</ol>`;$('#rules').showModal()}
$('.close').onclick=()=>$('#rules').close();$('#rules').addEventListener('click',e=>{if(e.target===$('#rules'))$('#rules').close()});document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>choose(b.dataset.game));document.querySelector('.tabs').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();choose(['bingo','roles','route','slang'][(['bingo','roles','route','slang'].indexOf(game)+(e.key==='ArrowRight'?1:3))%4]);$('#tab-'+game).focus()}});setup();
function slangSetup(){work.innerHTML=`<div class="boardhead"><div><h2>Правосленг</h2><p>Словарь подросткового сленга с примерами о правах.</p></div><a class="secondary" href="materials/pravosleng.pdf" target="_blank" rel="noopener">Читать PDF</a></div><div class="slangdictionary">${SLANG.map(c=>`<article class="slangentry"><h3>${esc(c.term)}</h3><p class="slangmeaning">${esc(c.meaning)}</p><p class="slangexample">${esc(c.example)}</p></article>`).join('')}</div>`}
